import {nextCue,distance,metrics,locate,fixStatus,hasArrived,validateRoute,encodeRoute,decodeRoute,formatDistance,simplify} from './core.js';
import {CONFIG,searchPlaces,snapToRoads,parseGPX,toGPX} from './services.js';
const $=id=>document.getElementById(id),txt=(id,value)=>$(id).textContent=value;
const symbols={plus:'＋',moon:'◐',help:'?',search:'⌕','arrow-right':'→',locate:'⊙',expand:'⛶',route:'⌁',phone:'▯',pin:'◎',pen:'✎',undo:'↶',check:'✓',x:'×','arrow-left':'←',navigation:'➤',share:'↗',upload:'↑',download:'↓',trash:'×',volume:'♪'};
document.querySelectorAll('[data-icon]').forEach(e=>{e.textContent=symbols[e.dataset.icon]||'•';e.setAttribute('aria-hidden','true');});
let toastTimer;
function toast(message){txt('toast',message);$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,6500);}
function safe(task){return async e=>{try{await task(e);}catch(err){toast(err.message||'Não foi possível concluir. Tente novamente.');}};}
const on=(id,fn,event='click')=>$(id).addEventListener(event,safe(fn));
const KEY='vai-comigo-routes-v1';let routes=[];
try{routes=JSON.parse(localStorage.getItem(KEY)||'[]').map(validateRoute);}catch{toast('Não foi possível ler as rotas salvas. Importe sua cópia de segurança.');}
function persist(next){try{localStorage.setItem(KEY,JSON.stringify(next));routes=next;}catch{throw Error('Não foi possível salvar neste navegador. Libere espaço ou baixe uma cópia da rota.');}}
function id(){return crypto.randomUUID?.()||'r'+Date.now()+Math.random().toString(36).slice(2);}
function storeRoute(r){r=validateRoute({...r,id:r.id||id()});persist([...routes.filter(x=>x.id!==r.id),r]);return r;}
try{document.body.classList.toggle('night',localStorage.getItem('vc-theme')==='night');}catch{}
on('theme-btn',()=>{document.body.classList.toggle('night');try{localStorage.setItem('vc-theme',document.body.classList.contains('night')?'night':'day');}catch{}});
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());
on('help-btn',()=>$('help-dialog').showModal());
const map=L.map('map',{zoomControl:false}).setView([-25.438,-49.32],12);
const tiles=L.tileLayer(CONFIG.tiles,{maxZoom:19,attribution:'© <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">OpenStreetMap</a>'}).addTo(map);
let tileError=false;tiles.on('tileerror',()=>{if(!tileError){tileError=true;txt('map-message','Mapa indisponível ou conexão fraca. O traçado continua visível.');$('map-message').hidden=false;}});
tiles.on('load',()=>{if(!tileError)$('map-message').hidden=true;});
const line=L.polyline([],{color:'#245de7',weight:6,opacity:.95}).addTo(map),markers=L.layerGroup().addTo(map);
let view='library',current=null,draft=null,drawMode='points',undo=[],revision=0,routeBusy=false;
let watch=null,navTimer=null,fix=null,previous=null,lastTime=null,following=true,voice=false,wake=null,lastSpoken='',lastAlert=0,arrived=false;
const time=(m,s)=>Math.max(1,Math.round(m/(s*1000/60)))+' min';
function show(name){view=name;for(const v of ['library','editor','detail'])$(v+'-view').hidden=v!==name;$('panel').classList.toggle('editor-panel',name==='editor');$('library-tab').classList.toggle('active',name!=='editor');$('new-tab').classList.toggle('active',name==='editor');$('panel').scrollTop=0;setDrawMode('points');if(name==='library'){current=null;line.setLatLngs([]);markers.clearLayers();renderLibrary();}map.invalidateSize();}
function fit(){const bounds=line.getBounds();if(bounds.isValid()){const mobile=innerWidth<=650;map.fitBounds(bounds,{paddingTopLeft:mobile?[35,125]:[425,100],paddingBottomRight:mobile?[45,Math.min(innerHeight*.50,430)]:[90,65],maxZoom:17,animate:false});}}
function marker(p,i,last,editable=false){const m=L.marker(p,{draggable:editable,icon:L.divIcon({className:'route-marker '+(i===0?'start':last?'end':''),html:String(i+1),iconSize:[29,29],iconAnchor:[14,14]})}).addTo(markers);if(editable){m.on('dragstart',()=>snapshot());m.on('dragend',()=>{const a=m.getLatLng();draft.points[i]=[a.lat,a.lng];changed();});}return m;}
function paint(points,editing=false){line.setLatLngs(points);markers.clearLayers();if(editing&&points.length<=100)points.forEach((p,i)=>marker(p,i,i===points.length-1,true));else if(points.length){marker(points[0],0,false);if(points.length>1)marker(points.at(-1),points.length-1,true);}}
function renderLibrary(){const list=$('route-list');list.replaceChildren();$('empty-state').hidden=routes.length>0;for(const r of routes){const b=document.createElement('button');b.className='route-card';const icon=document.createElement('div');icon.className='route-card-icon';icon.textContent='⌁';const d=document.createElement('div'),h=document.createElement('h2'),p=document.createElement('p');h.textContent=r.name;p.textContent=formatDistance(metrics(r.points).total)+' · '+r.points.length+' pontos';d.append(h,p);b.append(icon,d);b.onclick=()=>detail(r);list.append(b);}}
function detail(r){current=validateRoute(r);show('detail');paint(current.points);txt('detail-name',r.name);txt('detail-kind',r.mode==='roads'?'Ajustada às ruas · confira o trajeto':'Traçado manual · sem conversões');const m=metrics(r.points);txt('detail-distance',formatDistance(m.total));txt('detail-time',time(m.total,r.averageSpeed));txt('detail-notes',r.notes);$('detail-notes').hidden=!r.notes;const list=$('instructions');list.replaceChildren();for(const c of r.cues){const p=document.createElement('div');p.className='instruction-item';p.textContent=c.text;list.append(p);}fit();}
function edit(r=null){if(watch!==null)return;draft=r?structuredClone(r):{version:1,name:'Minha rota',points:[],cues:[],mode:'manual',averageSpeed:30,notes:''};undo=[];revision++;show('editor');$('route-name').value=draft.name;$('average-speed').value=draft.averageSpeed;$('route-notes').value=draft.notes;renderEditor();if(r)fit();}
function snapshot(){undo.push(structuredClone(draft));if(undo.length>35)undo.shift();}
function changed(){revision++;draft.mode='manual';draft.cues=[];renderEditor();}
function renderEditor(){paint(draft.points,true);const m=metrics(draft.points);txt('edit-distance',formatDistance(m.total));txt('edit-time',m.total?time(m.total,Number($('average-speed').value)):'—');$('save-btn').disabled=draft.points.length<2||m.total<5||routeBusy;$('snap-btn').disabled=draft.points.length<2||routeBusy;$('undo-btn').disabled=!undo.length;txt('route-kind',draft.mode==='roads'?'Ajustada às ruas · revise antes de salvar':'Traçado manual · sem instruções de conversão');$('route-kind').classList.toggle('routed',draft.mode==='roads');const list=$('waypoints');list.replaceChildren();const shown=draft.points.length<=40?draft.points:draft.points.filter((_,i)=>i===0||i===draft.points.length-1);shown.forEach((p,j)=>{const i=draft.points.length<=40?j:(j===0?0:draft.points.length-1);const row=document.createElement('div');row.className='waypoint';const n=document.createElement('span');n.className='point-number';n.textContent=i+1;const name=document.createElement('span');name.textContent=i===0?'Saída':i===draft.points.length-1?'Destino':'Passagem '+i;const del=document.createElement('button');del.textContent='×';del.setAttribute('aria-label','Remover ponto '+(i+1));del.onclick=()=>{snapshot();draft.points.splice(i,1);changed();};row.append(n,name,del);list.append(row);});}
function setDrawMode(mode){drawMode=mode;const drawing=view==='editor'&&mode==='free';document.body.classList.toggle('drawing',drawing);$('map').style.touchAction=drawing?'none':'';map.dragging[drawing?'disable':'enable']();$('point-mode').classList.toggle('selected',mode==='points');$('free-mode').classList.toggle('selected',mode==='free');txt('draw-help',drawing?'Arraste sobre o mapa para desenhar. Use “Por pontos” para mover o mapa.':'Toque no mapa para marcar a saída e os próximos pontos. Arraste os marcadores para ajustar.');}
map.on('click',e=>{if(view!=='editor'||drawMode!=='points'||routeBusy)return;if(draft.points.length>=20000)return toast('Limite de 20.000 pontos.');snapshot();draft.points.push([e.latlng.lat,e.latlng.lng]);changed();});
let stroke=null,strokeId=null;
$('map').addEventListener('pointerdown',e=>{if(view!=='editor'||drawMode!=='free'||routeBusy||e.target.closest('.leaflet-control'))return;e.preventDefault();snapshot();stroke=[];strokeId=e.pointerId;$('map').setPointerCapture(e.pointerId);const p=map.mouseEventToLatLng(e);stroke.push([p.lat,p.lng]);});
$('map').addEventListener('pointermove',e=>{if(!stroke||strokeId!==e.pointerId)return;e.preventDefault();const p=map.mouseEventToLatLng(e),a=[p.lat,p.lng];if(distance(stroke.at(-1),a)>3){stroke.push(a);line.setLatLngs([...draft.points,...stroke]);}});
function endStroke(){if(!stroke)return;draft.points=[...draft.points,...simplify(stroke,6)].slice(0,20000);stroke=null;strokeId=null;changed();}
$('map').addEventListener('pointerup',endStroke);$('map').addEventListener('pointercancel',endStroke);
function leaveEditor(){return view!=='editor'||draft.points.length===0||confirm('Sair do editor? Alterações não salvas serão perdidas.');}
on('new-btn',()=>edit());on('new-tab',()=>{if(watch!==null)return;if(leaveEditor())edit();});on('library-tab',()=>{if(watch===null&&leaveEditor())show('library');});on('cancel-edit',()=>{if(leaveEditor())show('library');});on('back-btn',()=>show('library'));on('edit-btn',()=>edit(current));
on('point-mode',()=>setDrawMode('points'));on('free-mode',()=>setDrawMode('free'));on('undo-btn',()=>{if(undo.length){draft=undo.pop();revision++;renderEditor();}});on('clear-btn',()=>{snapshot();draft.points=[];changed();});on('average-speed',renderEditor,'change');
on('snap-btn',async()=>{const version=revision,original=draft;snapshot();routeBusy=true;renderEditor();txt('snap-btn','Consultando as ruas…');try{const r=await snapToRoads(draft.points);if(version!==revision||draft!==original||view!=='editor')return;draft={...draft,points:r.points,cues:r.cues,mode:'roads'};revision++;renderEditor();toast('Confira o caminho azul. Use Desfazer se o ajuste não passar pelas ruas desejadas.');fit();}finally{routeBusy=false;txt('snap-btn','Ajustar às ruas');if(view==='editor')renderEditor();}});
on('save-btn',()=>{draft.name=$('route-name').value;draft.averageSpeed=Number($('average-speed').value);draft.notes=$('route-notes').value;current=storeRoute(draft);detail(current);toast('Caminho salvo neste aparelho.');});
on('delete-btn',()=>{if(confirm('Excluir “'+current.name+'” deste aparelho?')){persist(routes.filter(r=>r.id!==current.id));show('library');}});
on('fit-btn',fit);on('zoom-in',()=>map.zoomIn());on('zoom-out',()=>map.zoomOut());
on('search-form',async e=>{e.preventDefault();const q=$('search-input').value.trim();if(q.length<3)return;const button=$('search-btn');button.disabled=true;try{const results=await searchPlaces(q);const list=$('search-results');list.replaceChildren();list.hidden=false;if(!results.length)list.textContent='Nenhum lugar encontrado.';results.forEach(r=>{const b=document.createElement('button');b.className='search-result';b.textContent=r.display_name;b.onclick=()=>{map.setView([Number(r.lat),Number(r.lon)],16);list.hidden=true;};list.append(b);});}finally{button.disabled=false;}},'submit');
function download(content,name,type){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
on('export-gpx',()=>download(toGPX(current),'caminho.gpx','application/gpx+xml'));
on('share-btn',()=>{const u=new URL(location.href);u.hash='rota='+encodeRoute(current);$('share-url').value=u.href;const long=u.href.length>8000;txt('share-warning',long?'Este link é longo. Prefira baixar o arquivo JSON e enviá-lo.':'Quem receber o link poderá ver o caminho. Compartilhe apenas com quem você escolher.');$('native-share').disabled=long||!navigator.share;$('copy-share').disabled=long;$('share-dialog').showModal();});
on('copy-share',async()=>{try{await navigator.clipboard.writeText($('share-url').value);toast('Link copiado.');}catch{$('share-url').select();toast('Selecione e copie o link acima.');}});
on('native-share',async()=>{try{await navigator.share({title:current.name,url:$('share-url').value});}catch(e){if(e.name!=='AbortError')throw e;}});
on('download-json',()=>download(JSON.stringify(current,null,2),'caminho.json','application/json'));
function receive(r){r=validateRoute({...r,id:undefined});$('import-dialog').close();edit(r);toast('Rota recebida. Confira no mapa e toque em Salvar caminho.');}
function fromLink(value){let hash;try{hash=new URL(value).hash;}catch{throw Error('Cole o link completo da rota.');}const encoded=new URLSearchParams(hash.slice(1)).get('rota');if(!encoded)throw Error('O link não contém uma rota.');return decodeRoute(encoded);}
on('import-btn',()=>$('import-dialog').showModal());on('import-link',()=>receive(fromLink($('import-url').value.trim())));on('pick-file',()=>$('import-file').click());on('import-file',async()=>{const file=$('import-file').files[0];if(!file)return;try{if(file.size>4000000)throw Error('Arquivo grande demais (máximo 4 MB).');const content=await file.text();receive(file.name.toLowerCase().endsWith('.gpx')?parseGPX(content):validateRoute(JSON.parse(content)));}finally{$('import-file').value='';}},'change');
let gpsMarker=null,gpsCircle=null;
function drawFix(p){const latlng=[p.coords.latitude,p.coords.longitude];if(!gpsMarker){gpsMarker=L.marker(latlng,{icon:L.divIcon({className:'gps-marker',iconSize:[24,24],iconAnchor:[12,12]})}).addTo(map);gpsCircle=L.circle(latlng,{radius:p.coords.accuracy,color:'#2265ed',weight:1,fillOpacity:.07}).addTo(map);}gpsMarker.setLatLng(latlng);gpsCircle.setLatLng(latlng).setRadius(Math.min(5000,p.coords.accuracy));gpsMarker.getElement()?.classList.toggle('stale',fixStatus({timestamp:p.timestamp,accuracy:p.coords.accuracy})!=='ok');return latlng;}
function geoError(e){return e.code===1?'Localização bloqueada. Autorize o GPS nos ajustes do Safari/iPhone.':e.code===3?'O GPS demorou para responder. Aguarde em local aberto.':'Não foi possível obter a localização. Confira o GPS e a conexão.';}
on('locate-btn',()=>{if(!navigator.geolocation)throw Error('GPS indisponível. Abra o site por HTTPS.');navigator.geolocation.getCurrentPosition(p=>{drawFix(p);map.setView([p.coords.latitude,p.coords.longitude],16);},e=>toast(geoError(e)),{enableHighAccuracy:true,timeout:15000,maximumAge:0});});
function speak(text){if(!voice||!('speechSynthesis'in window)||document.hidden)return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='pt-BR';speechSynthesis.speak(u);}
async function requestWake(){try{if(navigator.wakeLock&&!document.hidden&&watch!==null)wake=await navigator.wakeLock.request('screen');}catch{toast('Mantenha a tela ligada durante o trajeto.');}}
function state(message,alert=false){txt('nav-state',message);$('nav-state').classList.toggle('alert',alert);}
function gpsWarning(message){$('resume-here').hidden=true;state(message,true);txt('nav-instruction','Pare em local seguro e confira');txt('nav-cue-distance','GPS SEM ORIENTAÇÃO');txt('nav-symbol','!');txt('nav-speed','—');txt('nav-remaining','—');txt('nav-time','—');if('speechSynthesis'in window)speechSynthesis.cancel();}
function navigate(p){if(watch===null)return;fix=p;const a=drawFix(p),quality=fixStatus({timestamp:p.timestamp,accuracy:p.coords.accuracy});txt('nav-quality','Precisão: ±'+Math.round(p.coords.accuracy)+' m · mantenha a tela ligada');if(quality!=='ok'){gpsWarning(quality==='stale'?'GPS desatualizado':'GPS impreciso — aguardando melhor sinal');return;}const m=locate(a,current.points,{previous,elapsed:lastTime?(p.timestamp-lastTime)/1000:1});lastTime=p.timestamp;const off=m.off>Math.max(35,p.coords.accuracy*1.5)||m.ambiguous;if(following)map.setView(a,Math.max(map.getZoom(),16),{animate:false});txt('nav-speed',Number.isFinite(p.coords.speed)&&p.coords.speed>=0?Math.round(p.coords.speed*3.6):'—');txt('nav-remaining',formatDistance(m.remaining));txt('nav-time',time(m.remaining,current.averageSpeed));$('resume-here').hidden=!off;if(off){state(m.ambiguous?'Confira o trecho para retomar':'Fora do caminho · sem recálculo',true);txt('nav-cue-distance',m.ambiguous?'CONFIRME SUA POSIÇÃO':'DESVIO DE '+formatDistance(m.off));txt('nav-instruction','Pare em local seguro e confira a rota');txt('nav-symbol','!');if(Date.now()-lastAlert>25000){speak('Pare em local seguro para conferir sua posição no caminho.');lastAlert=Date.now();}return;}previous=m.along;if(hasArrived(m,p.coords.accuracy,distance(a,current.points.at(-1)))){state('Você chegou ao final do caminho');txt('nav-instruction','Destino alcançado');txt('nav-cue-distance','CHEGADA');txt('nav-symbol','✓');if(!arrived)speak('Você chegou ao final do caminho.');arrived=true;return;}state('No caminho · rota fixa');const cumulative=metrics(current.points).cumulative;const cue=nextCue(current.cues,cumulative,m.along);if(cue){const remaining=Math.max(0,cumulative[cue.index]-m.along);txt('nav-cue-distance','EM '+formatDistance(remaining));txt('nav-instruction',cue.text);txt('nav-symbol',/esquerda/i.test(cue.text)?'↰':/direita/i.test(cue.text)?'↱':'↑');const key=cue.index+':'+(remaining<60?'near':'far');if(remaining<250&&key!==lastSpoken){speak('Em '+formatDistance(remaining)+', '+cue.text);lastSpoken=key;}}else{txt('nav-cue-distance','ACOMPANHE O TRAÇADO');txt('nav-instruction',current.mode==='manual'?'Siga o caminho azul no mapa':'Continue até o final da rota');txt('nav-symbol','↑');}}
on('start-btn',()=>{txt('start-route-warning',current.mode==='manual'?'Rota manual: não há instruções de virar nem verificação das ruas.':'Confira as conversões: os dados do mapa podem estar incompletos ou desatualizados.');$('start-dialog').showModal();});
on('confirm-start',()=>{if(!navigator.geolocation)throw Error('GPS indisponível. Acesse o site por HTTPS.');$('start-dialog').close();$('panel').hidden=true;$('search-area').hidden=true;$('map-tip').hidden=true;$('navigation-view').hidden=false;document.body.classList.add('navigating');setDrawMode('points');view='navigation';previous=null;lastTime=null;fix=null;lastSpoken='';lastAlert=0;arrived=false;following=true;state('Aguardando GPS');txt('nav-instruction','Aguarde sua localização');txt('nav-cue-distance','BUSCANDO GPS');txt('nav-quality','Mantenha o mapa aberto e a tela ligada.');for(const k of ['remaining','time','speed'])txt('nav-'+k,'—');watch=navigator.geolocation.watchPosition(navigate,e=>{fix=null;gpsWarning(geoError(e));toast(geoError(e));},{enableHighAccuracy:true,maximumAge:0,timeout:15000});requestWake();navTimer=setInterval(()=>{if(!fix||fixStatus({timestamp:fix.timestamp,accuracy:fix.coords.accuracy})==='stale'){gpsWarning('Aguardando posição atual do GPS');gpsMarker?.getElement()?.classList.add('stale');}},3000);});
function stop(){if(watch!==null)navigator.geolocation.clearWatch(watch);watch=null;clearInterval(navTimer);wake?.release().catch(()=>{});wake=null;if('speechSynthesis'in window)speechSynthesis.cancel();document.body.classList.remove('navigating');$('panel').hidden=false;$('search-area').hidden=false;$('map-tip').hidden=false;$('navigation-view').hidden=true;detail(current);}
on('resume-here',()=>{if(!fix||fixStatus({timestamp:fix.timestamp,accuracy:fix.coords.accuracy})!=='ok')throw Error('Aguarde um GPS preciso e atualizado.');if(confirm('Com a moto parada, confira sua posição no mapa. Retomar o trecho mais próximo? Em cruzamentos da própria rota, confira qual trecho deseja seguir.')){previous=null;lastTime=null;navigate(fix);}});
on('stop-btn',stop);on('voice-btn',()=>{if(!('speechSynthesis'in window))throw Error('Voz indisponível neste navegador.');voice=!voice;txt('voice-btn',voice?'♪ Voz ligada':'♪ Voz desligada');$('voice-btn').setAttribute('aria-pressed',String(voice));if(voice)speak('Avisos de voz ativados. Mantenha o aplicativo aberto.');else speechSynthesis.cancel();});
on('follow-btn',()=>{following=true;if(fix)map.setView([fix.coords.latitude,fix.coords.longitude],17);});map.on('dragstart',()=>following=false);
document.addEventListener('visibilitychange',()=>{if(watch!==null){if(document.hidden){fix=null;gpsWarning('Navegação pausada — volte ao aplicativo');}else{gpsWarning('Retomando GPS — aguarde posição atual');requestWake();}}});
window.addEventListener('online',()=>{tileError=false;tiles.redraw();toast('Conexão restabelecida.');});window.addEventListener('offline',()=>{txt('map-message','Sem internet. Mapas novos, busca e ajuste às ruas ficam indisponíveis.');$('map-message').hidden=false;});
window.addEventListener('beforeunload',e=>{if(watch!==null||(view==='editor'&&draft?.points.length)){e.preventDefault();e.returnValue='';}});
show('library');if(location.hash.startsWith('#rota=')){try{receive(fromLink(location.href));history.replaceState(null,'',location.pathname+location.search);}catch(e){toast(e.message);}}
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>toast('Não foi possível preparar o app para abrir sem internet.'));
