import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import fs from 'node:fs';
import * as core from '../core.js';import * as services from '../services.js';
// Controller tests: real app/core code, simulated DOM/Leaflet/GPS. Does not verify rendering.
class Element{
 constructor(){this.hidden=false;this.value='';this.textContent='';this.children=[];this.events={};this.style={};this.classes=new Set();this.classList={add:k=>this.classes.add(k),remove:k=>this.classes.delete(k),contains:k=>this.classes.has(k),toggle:(k,v)=>{const next=v??!this.classes.has(k);next?this.classes.add(k):this.classes.delete(k);return next;}};}
 addEventListener(name,fn){this.events[name]=fn;}setAttribute(){}append(...v){this.children.push(...v);}replaceChildren(...v){this.children=v;}showModal(){this.open=true;}close(){this.open=false;}select(){}setPointerCapture(){}closest(){return null;}click(){return this.events.click?.({preventDefault(){}})||this.onclick?.();}
}
function setup(){const html=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8');const elements=Object.fromEntries([...html.matchAll(/id="([^"]+)"/g)].map(m=>[m[1],new Element()]));elements['average-speed'].value='30';const doc={body:new Element(),hidden:false,events:{},getElementById:id=>{assert.ok(elements[id],'missing DOM id '+id);return elements[id];},querySelectorAll:()=>[],createElement:()=>new Element(),addEventListener(name,fn){this.events[name]=fn;}};
 const layer=()=>({points:[],events:{},addTo(){return this;},setLatLngs(p){this.points=p;return this;},getBounds(){return{isValid:()=>this.points.length>1};},clearLayers(){},on(n,f){this.events[n]=f;return this;},setLatLng(){return this;},setRadius(){return this;},getElement(){return new Element();},redraw(){}});
 const map={events:{},zoom:12,dragging:{enable(){},disable(){}},setView(a,z){this.center=a;this.zoom=z;return this;},getZoom(){return this.zoom;},fitBounds(){},invalidateSize(){},on(n,f){this.events[n]=f;},zoomIn(){},zoomOut(){},mouseEventToLatLng:e=>({lat:e.lat,lng:e.lng})};
 let gpsCallback,gpsError,timer;const saved=new Map();const context={...core,...services,console,crypto:{randomUUID:()=>String(Math.random())},document:doc,L:{map:()=>map,tileLayer:layer,polyline:layer,layerGroup:layer,marker:layer,circle:layer,divIcon:v=>v},localStorage:{getItem:k=>saved.get(k)||null,setItem:(k,v)=>saved.set(k,v)},navigator:{geolocation:{watchPosition(fn,err){gpsCallback=fn;gpsError=err;return 1;},clearWatch(){}}},location:{href:'https://example.test/vai-comigo/',hash:'',pathname:'/vai-comigo/',search:''},history:{replaceState(){}},innerWidth:390,innerHeight:844,confirm:()=>true,structuredClone,URL,Blob,Date,setTimeout:()=>1,clearTimeout(){},setInterval:fn=>{timer=fn;return 1;},clearInterval(){},addEventListener(){}};context.window=context;vm.createContext(context);const code=fs.readFileSync(new URL('../app.js',import.meta.url),'utf8').replace(/^import .*;\n/gm,'');vm.runInContext(code,context);return {context,doc,e:elements,map,saved,gps:p=>gpsCallback(p),geoError:e=>gpsError(e),tick:()=>timer()};}
const pos=(lat,lon,accuracy=10,age=0)=>({timestamp:Date.now()-age,coords:{latitude:lat,longitude:lon,accuracy,speed:0}});
async function makeRoute(s){await s.e['new-btn'].click();s.e['route-name'].value='Casa → café';s.map.events.click({latlng:{lat:-25.43,lng:-49.27}});s.map.events.click({latlng:{lat:-25.43,lng:-49.26}});await s.e['save-btn'].click();}
test('create, save, share, import, navigation, GPS loss and stop through actual event handlers',async()=>{const s=setup();await makeRoute(s);assert.equal(s.e['detail-name'].textContent,'Casa → café');assert.ok(s.saved.get('vai-comigo-routes-v1'));await s.e['share-btn'].click();const url=s.e['share-url'].value;assert.equal(core.decodeRoute(new URLSearchParams(new URL(url).hash.slice(1)).get('rota')).name,'Casa → café');await s.e['start-btn'].click();await s.e['confirm-start'].click();s.gps(pos(-25.43,-49.27));assert.match(s.e['nav-state'].textContent,/No caminho/);s.gps(pos(-25.43,-49.269,90));assert.match(s.e['nav-state'].textContent,/impreciso/);assert.equal(s.e['nav-remaining'].textContent,'—');s.gps(pos(-25.43,-49.269,10,20000));assert.match(s.e['nav-state'].textContent,/desatualizado/);s.geoError({code:1});assert.match(s.e['nav-state'].textContent,/bloqueada/);await s.e['stop-btn'].click();assert.equal(s.doc.body.classList.contains('navigating'),false);s.e['import-url'].value=url;await s.e['import-link'].click();assert.equal(s.e['route-name'].value,'Casa → café');});
test('storage failure keeps draft available and gives useful error',async()=>{const s=setup();s.context.localStorage.setItem=()=>{throw Error('quota');};await makeRoute(s);assert.match(s.e.toast.textContent,/Não foi possível salvar/);assert.equal(s.e['editor-view'].hidden,false);});
test('a distant rejoin requires explicit recovery and respects fixed geometry',async()=>{const s=setup();await makeRoute(s);await s.e['confirm-start'].click();s.gps(pos(-25.43,-49.269));s.gps(pos(-25.43,-49.264));assert.match(s.e['nav-state'].textContent,/retomar/);assert.equal(s.e['resume-here'].hidden,false);await s.e['resume-here'].click();assert.match(s.e['nav-state'].textContent,/No caminho/);assert.equal(JSON.parse(s.saved.get('vai-comigo-routes-v1'))[0].points.length,2);});
test('background transition suppresses directions until fresh GPS returns',async()=>{const s=setup();await makeRoute(s);await s.e['confirm-start'].click();s.gps(pos(-25.43,-49.27));s.doc.hidden=true;s.doc.events.visibilitychange();assert.match(s.e['nav-state'].textContent,/pausada/);s.doc.hidden=false;s.doc.events.visibilitychange();assert.match(s.e['nav-state'].textContent,/Retomando/);s.gps(pos(-25.43,-49.2698));assert.match(s.e['nav-state'].textContent,/No caminho/);});
